// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDPQyfPHue2TnN9KU3LBrAZfCT5TeBVK9c',
    appId: '1:741004167510:web:9436ea22863527ca382ef7',
    messagingSenderId: '741004167510',
    projectId: 'againfire',
    authDomain: 'againfire.firebaseapp.com',
    storageBucket: 'againfire.appspot.com',
    measurementId: 'G-PG89K3K3Y5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyACGBuBSm6BrLGFujzffh92e42aUPk-FlY',
    appId: '1:741004167510:android:dd8bb4aa13e62a96382ef7',
    messagingSenderId: '741004167510',
    projectId: 'againfire',
    storageBucket: 'againfire.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRPjSOCI1BtfKggl2yKuODYVd6lyL-Ozs',
    appId: '1:741004167510:ios:b5b3bf6e2b9a1449382ef7',
    messagingSenderId: '741004167510',
    projectId: 'againfire',
    storageBucket: 'againfire.appspot.com',
    iosBundleId: 'com.example.chaljaabhai',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRPjSOCI1BtfKggl2yKuODYVd6lyL-Ozs',
    appId: '1:741004167510:ios:b5b3bf6e2b9a1449382ef7',
    messagingSenderId: '741004167510',
    projectId: 'againfire',
    storageBucket: 'againfire.appspot.com',
    iosBundleId: 'com.example.chaljaabhai',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDPQyfPHue2TnN9KU3LBrAZfCT5TeBVK9c',
    appId: '1:741004167510:web:992843359269d743382ef7',
    messagingSenderId: '741004167510',
    projectId: 'againfire',
    authDomain: 'againfire.firebaseapp.com',
    storageBucket: 'againfire.appspot.com',
    measurementId: 'G-RC2HXQK5C5',
  );

}